FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
ENV DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
RUN npx prisma generate

EXPOSE 3000

RUN chmod +x /app/scripts/ensure-node-modules.sh

CMD ["sh", "/app/scripts/ensure-node-modules.sh"]
